#!/usr/bin/env python3
"""
runtime_state_freshness.py - generalized SYN detector for tracked runtime
state that should be regenerated by cron but was reverted by a deploy reset.

Inventory-driven. For each registered file:
  - Check mtime freshness against max_age_min.
  - If stale, call the regenerator script (Path A auto-heal inline).
  - After N consecutive heal failures, emit escalate so VIDAR consumer can
    route to LOKI dashboard work order (and eventually VIDAR-officer on
    oscillation).

Writes source=runtime_state_freshness to syn_inbox.jsonl. VIDAR consumer
has a DROP rule on RECOVERED messages; LOKI_ESCALATE is default for drift
alerts that didn't auto-heal.

Path A per project_loki_executor_path_b.md - SYN self-heals inline via the
inventory's regenerator command. Path B (clean LOKI executor with action
registry) is the future-better version; revisit when a 2nd monitor needs
non-systemctl auto-heal.
"""
import json
import os
import subprocess
import time
from datetime import datetime, timezone

WORKSPACE = "/root/.openclaw/workspace"
INBOX = f"{WORKSPACE}/syn_inbox.jsonl"
STATE_FILE = f"{WORKSPACE}/competition/runtime_state_freshness_state.json"

HEAL_TIMEOUT_SEC = 60
ESCALATE_AFTER_FAILURES = 2

# Inventory: each entry is a tracked runtime state file regenerated by cron.
# Path B will move `regen` into a safelisted registry keyed by action_type.
INVENTORY = [
    {
        "label":        "futures_day_leaderboard",
        "path":         f"{WORKSPACE}/competition/futures_day/futures_day_leaderboard.json",
        "max_age_min":  45,
        "regen":        ["python3", f"{WORKSPACE}/futures_day_leaderboard.py", "--json"],
    },
    {
        "label":        "futures_swing_leaderboard",
        "path":         f"{WORKSPACE}/competition/futures_swing/futures_swing_leaderboard.json",
        "max_age_min":  45,
        "regen":        ["python3", f"{WORKSPACE}/futures_swing_leaderboard.py", "--json"],
    },
    {
        "label":        "swing_leaderboard",
        "path":         f"{WORKSPACE}/competition/swing/swing_leaderboard.json",
        "max_age_min":  45,
        "regen":        ["python3", f"{WORKSPACE}/swing_leaderboard.py", "--json"],
    },
    {
        "label":        "polymarket_leaderboard",
        "path":         f"{WORKSPACE}/competition/polymarket/polymarket_leaderboard.json",
        "max_age_min":  45,
        "regen":        ["python3", f"{WORKSPACE}/polymarket_leaderboard.py", "--json"],
    },
]


def load_state():
    if os.path.isfile(STATE_FILE):
        try:
            return json.load(open(STATE_FILE))
        except Exception:
            pass
    return {}


def save_state(s):
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    tmp = STATE_FILE + ".tmp"
    with open(tmp, "w") as f:
        json.dump(s, f, indent=2)
    os.replace(tmp, STATE_FILE)


def inbox_write(msg, severity):
    rec = {
        "ts":       datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M"),
        "source":   "runtime_state_freshness",
        "severity": severity,
        "msg":      msg[:2000],
    }
    with open(INBOX, "a") as f:
        f.write(json.dumps(rec) + "\n")


def file_age_min(path):
    if not os.path.isfile(path):
        return None
    return (time.time() - os.path.getmtime(path)) / 60


def run_regen(cmd):
    try:
        res = subprocess.run(
            cmd,
            timeout=HEAL_TIMEOUT_SEC,
            capture_output=True,
            text=True,
        )
        return res.returncode == 0, f"rc={res.returncode}"
    except subprocess.TimeoutExpired:
        return False, f"timeout>{HEAL_TIMEOUT_SEC}s"
    except Exception as e:
        return False, f"exception:{type(e).__name__}:{e}"


def check_one(entry, state):
    label = entry["label"]
    path  = entry["path"]
    max_age = entry["max_age_min"]
    prev = state.get(label, {"consec_failures": 0, "alerted": False})

    age = file_age_min(path)
    if age is None:
        # missing is a kind of drift too
        status = "missing"
        stale  = True
    elif age > max_age:
        status = f"stale:{age:.0f}min>{max_age}min"
        stale  = True
    else:
        status = f"fresh:{age:.0f}min"
        stale  = False

    if not stale:
        if prev.get("alerted"):
            inbox_write(
                f"[OPS/runtime_state_freshness] {label} RECOVERED ({status}).",
                severity="info",
            )
        state[label] = {"consec_failures": 0, "alerted": False, "last_check": datetime.now(timezone.utc).isoformat()}
        return f"{label}:{status}"

    # Stale — attempt auto-heal (Path A inline regen).
    ok, detail = run_regen(entry["regen"])
    if ok:
        # Verify the regen actually updated the file
        new_age = file_age_min(path)
        if new_age is not None and new_age <= max_age:
            if prev.get("alerted"):
                inbox_write(
                    f"[OPS/runtime_state_freshness] {label} self-healed (was {status}, now fresh:{new_age:.0f}min).",
                    severity="info",
                )
            state[label] = {"consec_failures": 0, "alerted": False, "last_check": datetime.now(timezone.utc).isoformat()}
            return f"{label}:healed({status}->fresh)"
        else:
            # Regen exited 0 but file is still stale — no-op healer
            ok = False
            detail = f"regen_noop:file_still_{status}"

    # Heal failed — count toward escalation
    fails = prev.get("consec_failures", 0) + 1
    state[label] = {
        "consec_failures": fails,
        "alerted":         True,
        "last_fail_detail": detail,
        "last_status":     status,
        "last_check":      datetime.now(timezone.utc).isoformat(),
    }
    if fails >= ESCALATE_AFTER_FAILURES and not prev.get("escalated"):
        inbox_write(
            f"[OPS/runtime_state_freshness] {label} stale and auto-heal failed {fails}x.\n"
            f"File: {path}\n"
            f"Status: {status}\n"
            f"Last regen result: {detail}\n"
            f"Cmd: {' '.join(entry['regen'])}",
            severity="error",
        )
        state[label]["escalated"] = True
    return f"{label}:FAIL({status},heal:{detail})"


def main():
    state = load_state()
    summary = []
    for entry in INVENTORY:
        summary.append(check_one(entry, state))
    save_state(state)
    ts = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z")
    print(f"[{ts}] " + " | ".join(summary))


if __name__ == "__main__":
    main()
